sonar.projectKey=sofiaconst_2is70-project
sonar.organization=sofiaconst
sonar.host.url=https://sonarcloud.io

sonar.sources=app/src/main/java
sonar.tests=app/src/test/java,app/src/androidTest/java
sonar.test.inclusions=**/*Test*.java,**/*Test*.kt

sonar.java.binaries=app/build/tmp/kotlin-classes/debug,app/build/intermediates/javac/debug/classes
sonar.junit.reportPaths=app/build/test-results/testDebugUnitTest
sonar.coverage.jacoco.xmlReportPaths=app/build/reports/jacoco/jacocoUnitTestReport/jacocoUnitTestReport.xml

sonar.exclusions=**/R.class,**/R$*.class,**/BuildConfig.*,**/Manifest*.*