sonar.projectKey=sofiaconst_2is70-project
sonar.organization=sofiaconst
sonar.host.url=https://sonarcloud.io

sonar.sources=app/src/main/java,app/src/main/kotlin
sonar.tests=app/src/test/java,app/src/test/kotlin,app/src/androidTest/java,app/src/androidTest/kotlin
sonar.test.inclusions=**/*Test*.kt,**/*Test*.java

sonar.java.binaries=app/build/tmp/kotlin-classes/debug,app/build/intermediates/javac/debug/classes
sonar.junit.reportPaths=app/build/test-results/testDebugUnitTest
sonar.coverage.jacoco.xmlReportPaths=app/build/reports/jacoco/jacocoTestReport/jacocoTestReport.xml

sonar.exclusions=**/R.class,**/R$*.class,**/BuildConfig.*,**/Manifest*.*