name: SonarCloud Fast

on:
  push:
  pull_request:

jobs:
  sonarcloud:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: EduView

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: gradle

      - name: Make Gradle executable
        run: chmod +x gradlew

      - name: Run unit tests
        run: ./gradlew clean testDebugUnitTest --info

      - name: SonarCloud scan
        uses: SonarSource/sonarqube-scan-action@v7
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          projectBaseDir: EduView